kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: FREG_MQ_METRICS_SECURE_QUEUEMANAGER
      value: {{ FREG_MQ_METRICS_SECURE_QUEUEMANAGER }}
    - name: FREG_MQ_METRICS_SECURE_CHANNEL_NAME
      value: {{ FREG_MQ_METRICS_SECURE_CHANNEL_NAME }}
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ INGRESS }}
  liveness:
    path: /actuator/health/liveness
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /actuator/health/readiness
    initialDelay: 20
    timeout: 3
  prometheus:
    enabled: true
    path: /actuator/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVFREGMQMETRICS }}
        mountPath: "/secrets/serviceuser/srvfregmqmetrics"
      - kvPath: {{ SRVMQINQUIRE }}
        mountPath: "/secrets/serviceuser/srvmqinquire"
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 60m
      memory: 256Mi
    limits:
      memory: 512Mi
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki