kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:

    - name: FREG_MQ_METRICS_SECURE_QUEUEMANAGER
      value: {{ FREG_MQ_METRICS_SECURE_QUEUEMANAGER }}
    - name: FREG_MQ_METRICS_SECURE_CHANNEL_NAME
      value: {{ FREG_MQ_METRICS_SECURE_CHANNEL_NAME }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  leaderElection: true
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 1536Mi
    requests:
      cpu: 60m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVFREGMQMETRICS }}
        mountPath: "/secrets/serviceuser/srvfregmqmetrics"
      - kvPath: {{ SRVMQINQUIRE }}
        mountPath: "/secrets/serviceuser/srvmqinquire"
